### ISSUE TITLE
push minimal server code 

### ISSUE THREAD

**Issue by sam-gaylert** [nyu-software-engineering/trading-dashboard#13]
stand up a basic express.js backend to start working on

## estimated work:
S

## acceptance criteria:
- [x] passes code styling and review 
- [x] works as a basic service that we can test a minimal frontend with

**Comment by sam-gaylert** [comment]
we should coordinate on who will be making the initial commit

I can put something up soon, but I wont have time until later this week

**Comment by uwncksh** [comment]
I could help build up the basic skeleton for the unit testing, I will have the most time on Wed and Thurs this week to work on it if anyone wants to write together.
