### ISSUE TITLE
install npm

### ISSUE THREAD

**Issue by sam-gaylert** [nyu-software-engineering/trading-dashboard#20]
everyone should install npm so that we can easily coordinate our project environments and use the same version

[link to download](https://www.npmjs.com/get-npm)

## acceptance criteria

- [x] everyone has installed npm or has notified the group of issues

## estimated work

XS

**Comment by itcarrillo** [comment]
done

**Comment by jxupower** [comment]
done

**Comment by gurusawhney** [comment]
done
