### ISSUE TITLE
Decide collaboratively which user story to be included

### ISSUE THREAD

**Issue by uwncksh** [nyu-software-engineering/trading-dashboard#45]
Example case to start developing project: 
https://itunes.apple.com/us/app/clarity-money-budget-manager/id1148133022?mt=8

**Comment by sam-gaylert** [comment]
I dont think this is necessarily a spike that we need. I think this is just part of our sprint planning. I'm closing this for now, but will reopen if I am wrong

**Comment by uwncksh** [comment]
am closing it, just opened for new ideas to start Sprint1, for now, the team is concentrating on API, registration and UI before Jenkins integration
