### ISSUE TITLE
As a developer, I want to use D3, bootstrap, react.js, and a webpack (grunt) for the frontend, so that it looks nice to the user

### ISSUE THREAD

**Issue by sam-gaylert** [nyu-software-engineering/trading-dashboard#6]
Acceptance criteria:
- [ ] Created server
- [ ] Set these libraries up in server env
- [ ] Document setup so that those who are not familiar can get the env running 

Estimate work:
Large

**Comment by bloombar** [comment]
@nyu-software-engineering/spring-2019-trading-dashboard - this is a spike, not a user story.... please double-check your issue labels and make sure they're accurate.
