### ISSUE TITLE
Restructure App.js to render Home initially and register/login on navbar click

### ISSUE THREAD

**Issue by itcarrillo** [nyu-software-engineering/trading-dashboard#93]
## Acceptance Criteria

- [x] Can navigate to login and register components by clicking buttons on navbar
- [x] Can navigate back to home by clicking home on navbar

## Estimated Work

M

**Comment by ennb339** [comment]
Render Home with intros/trending albums and register/login on the navbar
Reconstruct the register/login procedure as follows (now it asks register/login first): 
- first click (from localhost): home page (adding more intro-features) with nav bar directing to login/register
- second click (on register/login): after register/login direct to user album gallery
- third click (on home): navigate back to the main/home page
